version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: python manage.py setup_dev
workflows:
  version: 2
  test:
    jobs:
      - test
